# Generated by Django 4.2.3 on 2023-07-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to',
        ),
    ]
