# Generated by Django 4.2.3 on 2023-07-30 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_remove_message_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messenger.room'),
            preserve_default=False,
        ),
    ]
