# Generated by Django 4.2.3 on 2023-07-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_message_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommembers',
            old_name='user',
            new_name='member',
        ),
    ]
